version: '3.1'

services:

  minio:
    image: minio/minio
    container_name: minio4php
    restart: unless-stopped
    ports:
      - 9090:9000
      - 9091:9001
    command: server --console-address ':9001' /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

  websvr:
    build: ./work
    container_name: web4minio
    restart: unless-stopped
    volumes:
      - ./work/src:/var/www/html
    ports:
      - 8081:80
    links:
      - minio
    depends_on:
      - minio
    environment:
      UPLOAD_LIMIT: 20M
